version: 2
updates:
  # For Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  # Optionally, for GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # For Dockerfile updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
